import {state,load,save,replace,fresh,rate,mastery} from './store.js';
import {esc,markdown} from './math.js';
export const app=document.querySelector('#app');
export let data={};let mode='home',cardIndex=0,flipped=false,onKey=()=>{},cleanup=()=>{};
export const sections=['1.1','1.3','1.4','1.5','1.6','1.7','2.1'];
export const options=(list,value='')=>list.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x||'All')}</option>`).join('');
export function register(key,stop=()=>{}){onKey=key;cleanup=stop;}
function home(){const seen=Object.keys(state.flashcards).length,done=Object.values(state.problems).filter(p=>p.attempts.length).length,best=Math.max(0,...state.rapidfire.sessions.map(s=>s.score)),m=data.topics.reduce((n,t)=>n+mastery(t.id,data.flashcards,data.problems).mastery,0)/(data.topics.length||1);const modes=[['flashcards','Flashcards','Flip cards, then Learn: multiple choice with know / don\'t know.',`${seen} / ${data.flashcards.length} cards studied`],['rapidfire','Rapid-fire','Build speed. Make the symbols automatic.',`Best score ${best}`],['report','Weakness report','Find the gaps. Read your class notes.',`${Math.round(m*100)}% overall mastery`],['problems','Problem grind','Write the proof. Check every step.',`${done} / ${data.problems.length} problems attempted`]];app.innerHTML=`<div class="eyebrow">Test 1 · September 16 · Rosen, 8th edition</div><h1>A clear head.<br>A solid proof.</h1><p class="lead">Start with recall, build speed, then put it on paper. Your class conventions, one focused study session at a time.</p><div class="grid">${modes.map((m,i)=>`<a class="mode-card" href="#${m[0]}"><span class="num">0${i+1} ${i===(seen<30?0:!state.rapidfire.sessions.length?1:done?3:2)?'· RECOMMENDED NEXT':''}</span><h2>${m[1]}</h2><p>${m[2]}</p><small>${m[3]}</small></a>`).join('')}</div><p class="muted">Scope: §§1.1, 1.3–1.7, 2.1 through power sets. Propositional inference only. ℕ includes 0.</p>`;}
export const setNames={'1.1':'Propositional logic','1.3':'Equivalences & laws','1.4':'Predicates & quantifiers','1.5':'Nested quantifiers','1.6':'Rules of inference','1.7':'Proof methods','2.1':'Sets'};
const learnOf=c=>state.flashcards[c.id]?.learn||'new',secOf=c=>c.id.split('-')[1];
export function setCards(sec){const order=Object.fromEntries(data.topics.map(t=>[t.id,t.order]));return data.flashcards.filter(c=>secOf(c)===sec).sort((a,b)=>(order[a.topic]||0)-(order[b.topic]||0)||a.priority-b.priority);}
const tally=cs=>{const n={known:0,learning:0,new:0};for(const c of cs)n[learnOf(c)]++;return n;};
function sets(){const rows=sections.map(sec=>{const cs=setCards(sec),n=tally(cs);return {sec,cs,n,pct:cs.length?100*n.known/cs.length:0};}),next=rows.find(r=>r.n.known<r.cs.length)||rows[0];
 app.innerHTML=`<div class="eyebrow">01 / Recall</div><h1>Flashcard sets</h1><p class="lead">One set per section, like a Quizlet folder. Flip through a set, mark each card, then run Learn on it before moving on.</p><div class="grid sets">${rows.map(r=>`<div class="mode-card set${r===next?' next':''}"><span class="num">§${r.sec}${r===next?' · UP NEXT':''}</span><h2>${esc(setNames[r.sec])}</h2><p>${r.cs.length} cards · ${r.n.known} known · ${r.n.learning} still learning · ${r.n.new} new</p><div class="meter"><span style="width:${r.pct}%"></span></div><small>${esc(data.topics.filter(t=>t.section===r.sec).sort((a,b)=>a.order-b.order).map(t=>t.title).join(' · '))}</small><div class="toolbar"><a href="#flashcards/${r.sec}"><button class="primary">Flashcards</button></a><a href="#flashcards/learn/${r.sec}"><button>Learn</button></a></div></div>`).join('')}</div>`;register(e=>{if(/^[1-7]$/.test(e.key))location.hash='flashcards/'+sections[+e.key-1];});}
let deckSec='',deckList=[],deckDone=[];
function deck(sec){if(sec!==deckSec){deckSec=sec;deckList=setCards(sec);deckDone=[];cardIndex=0;flipped=false;}const all=setCards(sec),n=tally(all),c=deckList[cardIndex],name=setNames[sec]||sec,head=`<div class="eyebrow">01 / Recall · §${esc(sec)}</div><h1>${esc(name)}</h1><div class="toolbar"><a href="#flashcards">← All sets</a> · <strong>Flashcards</strong> · <a href="#flashcards/learn/${esc(sec)}">Learn this set</a> · <a href="#rapidfire">Rapid-fire →</a></div><div class="meter" aria-label="Known cards"><span style="width:${all.length?100*n.known/all.length:0}%"></span></div><p class="muted">${n.known} known · ${n.learning} still learning · ${n.new} new · card ${Math.min(cardIndex+1,deckList.length)} / ${deckList.length}</p>`;
 if(!c){const known=deckDone.filter(d=>d.known).length,learning=deckDone.filter(d=>!d.known).map(d=>d.card),i=sections.indexOf(sec),nextSec=sections[i+1];app.innerHTML=head+`<div class="panel center"><h2>Set complete: ${known} known, ${learning.length} still learning.</h2><p class="muted">${learning.length?'Go again with only the cards you missed, or lock it in with Learn.':'Every card in this pass was marked known.'}</p><div class="toolbar center">${learning.length?`<button class="primary" id="redo">Review the ${learning.length} still learning</button>`:''}<a href="#flashcards/learn/${esc(sec)}"><button ${learning.length?'':'class="primary"'}>Learn this set</button></a><button id="restart">Restart set</button>${nextSec?`<a href="#flashcards/${nextSec}"><button>Next set: §${nextSec} →</button></a>`:'<a href="#rapidfire"><button>Rapid-fire →</button></a>'}</div></div>`;const on=(id,f)=>{const el=document.getElementById(id);if(el)el.onclick=f;};on('redo',()=>{deckList=learning;deckDone=[];cardIndex=0;flipped=false;deck(sec);});on('restart',()=>{deckList=setCards(sec);deckDone=[];cardIndex=0;flipped=false;deck(sec);});register(e=>{if(e.key==='Enter'&&learning.length)document.getElementById('redo').click();});return;}
 const status=state.flashcards[c.id]?.learn==='known'?'Marked known':state.flashcards[c.id]?.learn==='learning'?'Marked still learning':'Not yet marked';
 app.innerHTML=head+`<div class="card-scene"><div class="card-flip${flipped?' flipped':''}" id="flip" role="button" tabindex="0" aria-label="Flip flashcard"><div class="face front"><small>${esc(data.topics.find(t=>t.id===c.topic)?.title||c.topic)}</small><div>${esc(c.front)}</div><small>Space to reveal</small></div><div class="face back"><small>${esc(c.front)}</small><div>${markdown(c.back)}</div></div></div></div><div class="toolbar center mark"><button id="dont">← Don't know</button><button id="know" class="primary">Know →</button></div><p class="muted center">${status}. Arrow keys mark; Space flips.</p>`;
 let leaving=false;const flip=()=>{if(leaving)return;flipped=!flipped;document.querySelector('#flip').classList.toggle('flipped',flipped);},mark=known=>{if(leaving)return;leaving=true;rate(c.id,known?'good':'again',known?'known':'learning');deckDone.push({card:c,known});document.querySelector('.card-scene').classList.add(known?'out-right':'out-left');setTimeout(()=>{flipped=false;cardIndex++;deck(sec);},220);};
 document.querySelector('#flip').onclick=flip;document.querySelector('#know').onclick=()=>mark(true);document.querySelector('#dont').onclick=()=>mark(false);
 register(e=>{if(e.key===' '){e.preventDefault();flip();}if(e.key==='ArrowRight'){e.preventDefault();mark(true);}if(e.key==='ArrowLeft'){e.preventDefault();mark(false);}});}
async function route(){cleanup();cleanup=()=>{};onKey=()=>{};const sub=location.hash.slice(1).split('/')[1];mode=location.hash.slice(1).split('/')[0]||'home';if(mode==='home')home();else if(mode==='flashcards'){const parts=location.hash.slice(1).split('/');if(sub==='learn'){const m=await import('./learn.js');await m.learn(parts[2]||'');}else if(sections.includes(sub))deck(sub);else sets();}else if(mode==='rapidfire'){const m=await import('./rapidfire.js');m.setup();}else if(mode==='report'||mode==='problems'){try{const m=await import('./study.js');m[mode]();}catch{app.innerHTML='<h1>Content is being assembled</h1><p>Flashcards and rapid-fire are available now. The study guide and problem workspace arrive in Phase 4.</p>';}}else if(mode==='sources')app.innerHTML=`<h1>Sources & scope</h1><p>Test 1: September 16, 2026. Closed book, closed notes, no technology.</p><p>§§1.1, 1.3, 1.4, 1.5, 1.6 (propositional inference only), 1.7, 2.1 before Cartesian products.</p><p>Use all of Table 6. From Tables 7/8 cite only conditional-disjunction, contrapositive, and the biconditional definition.</p><p><a href="materials/HANDWRITTEN_NOTES_TRANSCRIPTION.md">Handwritten notes transcription</a> · <a href="materials/pdf/">Original PDFs</a> · <a href="materials/handwritten-pdf/">Handwritten PDFs</a> · <a href="SPEC.md">Specification</a> · <a href="DECISIONS.md">Content decisions</a></p>`;else home();window.scrollTo(0,0);}
document.querySelector('#shortcutBody').innerHTML='<p>Global: Esc → home; ? → shortcuts. Home: 1–4 → modes.</p><p>Sets: 1–7 open a section. Cards: Space flips; → Know; ← Don&#39;t know; Enter on the summary reviews the still-learning cards.</p><p>Learn: 1–4 choose an answer; → I know it; ← still learning; Enter accepts the highlighted choice or starts the next round.</p><p>Rapid-fire: type to answer; Enter submits; after a miss, Enter or Space continues; Escape ends the session. Miss bank: ←/→ move between misses.</p><p>Problems: N/P next/previous; S solution; H hint; 1/2/3 Wrong/Partly/Right. Shortcuts stay inactive in your scratch area.</p><h3>Typed aliases</h3><p>¬: ~, !, not · ∧: ^, &, and · ∨: v, |, or · →: ->, => · ↔: <->, iff · ∀: forall, A · ∃: exists, E · ≤: <= · ≥: >= · ≠: !=. Use x^2 for a numeric power. Parentheses define scope.</p><p>T/true, F/false; y/yes, n/no. Laws: dm, dn, dist, comm, assoc, idem, identity, dom, abs, neg, 7.1, implication, contrapositive, biconditional. Rules: mp, mt, hs, ds, add, simp, conj, res; invalid/fallacy. Methods: direct/d, contraposition/cp, contradiction/cd, contradiction of an implication/ci, biconditional/iff, tfae, counterexample/ce.</p>';
const dialog=document.querySelector('#shortcuts');document.querySelector('#help').onclick=()=>dialog.showModal();document.querySelector('#closeHelp').onclick=()=>dialog.close();
document.addEventListener('keydown',e=>{if(dialog.open)return;if(e.key==='Escape'){onKey(e);if(!e.defaultPrevented)location.hash='home';return;}const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if(e.key==='?'&&!typing){dialog.showModal();return;}if(mode==='rapidfire'){onKey(e);return;}if(typing)return;if(mode==='home'&&/^[1-4]$/.test(e.key))location.hash=['flashcards','rapidfire','report','problems'][+e.key-1];else onKey(e);});
document.querySelector('#theme').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.settings.theme==='light');save();};
document.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='math381-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.querySelector('#import').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const s=JSON.parse(await f.text());const {validate}=await import('./store.js');validate(s);if(confirm('Replace current progress with this import?')){replace(s);document.body.classList.toggle('light',state.settings.theme==='light');route();}}catch(err){alert(err.message);}e.target.value='';};
document.querySelector('#reset').onclick=()=>{if(confirm('Erase all saved study progress? Export first if you want a backup.')){replace(fresh());document.body.classList.remove('light');route();}};
try{load();document.body.classList.toggle('light',state.settings.theme==='light');const names=['topics','flashcards','rapidfire','problems'];const values=await Promise.all(names.map(async n=>{const r=await fetch('content/'+n+'.json');if(!r.ok)throw Error(n+' could not be loaded');return r.json();}));data=Object.fromEntries(names.map((n,i)=>[n,values[i]]));addEventListener('hashchange',route);route();}catch(e){app.innerHTML='<h1>Could not open the study desk</h1><p class="error">'+esc(e.message)+'</p><p>Run <code>python3 -m http.server 8000</code> in the workspace and open <a href="http://localhost:8000">localhost:8000</a>. If saved progress is corrupt, export a backup from browser storage before using Reset.</p>';}
