import {state,load,save,replace,fresh,rate,mastery} from './store.js';
import {esc,markdown} from './math.js';
export const app=document.querySelector('#app');
export let data={};let mode='home',cardIndex=0,flipped=false,cardFilter={section:'',priority:'',cram:false},onKey=()=>{},cleanup=()=>{};
export const sections=['1.1','1.3','1.4','1.5','1.6','1.7','2.1'];
export const options=(list,value='')=>list.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x||'All')}</option>`).join('');
export function register(key,stop=()=>{}){onKey=key;cleanup=stop;}
function home(){const seen=Object.keys(state.flashcards).length,done=Object.values(state.problems).filter(p=>p.attempts.length).length,best=Math.max(0,...state.rapidfire.sessions.map(s=>s.score)),m=data.topics.reduce((n,t)=>n+mastery(t.id,data.flashcards,data.problems).mastery,0)/(data.topics.length||1);const modes=[['flashcards','Flashcards','Learn the language. Recall the rules.',`${seen} / ${data.flashcards.length} cards studied`],['rapidfire','Rapid-fire','Build speed. Make the symbols automatic.',`Best score ${best}`],['report','Weakness report','Find the gaps. Read your class notes.',`${Math.round(m*100)}% overall mastery`],['problems','Problem grind','Write the proof. Check every step.',`${done} / ${data.problems.length} problems attempted`]];app.innerHTML=`<div class="eyebrow">Test 1 · September 16 · Rosen, 8th edition</div><h1>A clear head.<br>A solid proof.</h1><p class="lead">Start with recall, build speed, then put it on paper. Your class conventions, one focused study session at a time.</p><div class="grid">${modes.map((m,i)=>`<a class="mode-card" href="#${m[0]}"><span class="num">0${i+1} ${i===(seen<30?0:!state.rapidfire.sessions.length?1:done?3:2)?'· RECOMMENDED NEXT':''}</span><h2>${m[1]}</h2><p>${m[2]}</p><small>${m[3]}</small></a>`).join('')}</div><p class="muted">Scope: §§1.1, 1.3–1.7, 2.1 through power sets. Propositional inference only. ℕ includes 0.</p>`;}
function cards(){const all=data.flashcards.filter(c=>(!cardFilter.section||c.id.startsWith('fc-'+cardFilter.section+'-'))&&(!cardFilter.priority||c.priority==cardFilter.priority));if(!cardFilter.cram)all.sort((a,b)=>(state.flashcards[a.id]?.box||1)-(state.flashcards[b.id]?.box||1)||(state.flashcards[a.id]?.lastSeen||0)-(state.flashcards[b.id]?.lastSeen||0));cardIndex=(cardIndex+all.length)%(all.length||1);const c=all[cardIndex],boxes=[1,2,3,4].map(b=>all.filter(c=>(state.flashcards[c.id]?.box||1)===b).length);app.innerHTML=`<div class="eyebrow">01 / Recall</div><h1>Flashcards</h1><div class="toolbar"><label>Section <select id="fcSection">${options(['',...sections],cardFilter.section)}</select></label><label>Priority <select id="fcPriority">${options(['','1','2','3'],cardFilter.priority)}</select></label><label><input id="cram" type="checkbox" ${cardFilter.cram?'checked':''}> Cram all</label></div><p class="muted">Boxes 1–4: ${boxes.join(' / ')} · ${boxes[0]} cards due · ${all.length?cardIndex+1:0} / ${all.length}</p>${c?`<div class="panel card-face" id="flip" role="button" tabindex="0" aria-label="Flip flashcard"><small>${esc(data.topics.find(t=>t.id===c.topic)?.title||c.topic)}</small><div>${esc(c.front)}</div>${flipped?`<div class="back">${markdown(c.back)}</div>`:'<small>Space to reveal</small>'}</div><div class="toolbar"><button id="prev">← Previous</button><button id="next">Next →</button>${['Again','Hard','Good','Easy'].map((x,i)=>`<button data-rating="${x.toLowerCase()}" ${flipped?'':'disabled'}>${i+1} ${x}</button>`).join('')}</div>`:'<p>No cards match these filters.</p>'}`;for(const [id,key] of [['fcSection','section'],['fcPriority','priority'],['cram','cram']])document.getElementById(id).onchange=e=>{cardFilter[key]=key==='cram'?e.target.checked:e.target.value;cardIndex=0;flipped=false;cards();};const flip=()=>{flipped=!flipped;cards();},move=n=>{cardIndex+=n;flipped=false;cards();},grade=r=>{if(!flipped||!c)return;rate(c.id,r);flipped=false;if(cardFilter.cram)cardIndex++;else cardIndex=0;cards();};if(c){document.querySelector('#flip').onclick=flip;document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>grade(b.dataset.rating));}register(e=>{if(e.key===' '){e.preventDefault();flip();}if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(/^[1-4]$/.test(e.key))grade(['again','hard','good','easy'][+e.key-1]);});}
async function route(){cleanup();cleanup=()=>{};onKey=()=>{};mode=location.hash.slice(1).split('/')[0]||'home';if(mode==='home')home();else if(mode==='flashcards')cards();else if(mode==='rapidfire'){const m=await import('./rapidfire.js');m.setup();}else if(mode==='report'||mode==='problems'){try{const m=await import('./study.js');m[mode]();}catch{app.innerHTML='<h1>Content is being assembled</h1><p>Flashcards and rapid-fire are available now. The study guide and problem workspace arrive in Phase 4.</p>';}}else if(mode==='sources')app.innerHTML=`<h1>Sources & scope</h1><p>Test 1: September 16, 2026. Closed book, closed notes, no technology.</p><p>§§1.1, 1.3, 1.4, 1.5, 1.6 (propositional inference only), 1.7, 2.1 before Cartesian products.</p><p>Use all of Table 6. From Tables 7/8 cite only conditional-disjunction, contrapositive, and the biconditional definition.</p><p><a href="materials/HANDWRITTEN_NOTES_TRANSCRIPTION.md">Handwritten notes transcription</a> · <a href="materials/pdf/">Original PDFs</a> · <a href="materials/handwritten-pdf/">Handwritten PDFs</a> · <a href="SPEC.md">Specification</a> · <a href="DECISIONS.md">Content decisions</a></p>`;else home();window.scrollTo(0,0);}
document.querySelector('#shortcutBody').innerHTML='<p>Global: Esc → home; ? → shortcuts. Home: 1–4 → modes.</p><p>Cards: Space flip; 1 Again, 2 Hard, 3 Good, 4 Easy; ←/→ navigate.</p><p>Rapid-fire: type to answer; Enter submits; Escape ends the session.</p><p>Problems: N/P next/previous; S solution; H hint; 1/2/3 Wrong/Partly/Right. Shortcuts stay inactive in your scratch area.</p><h3>Typed aliases</h3><p>¬: ~, !, not · ∧: ^, &, and · ∨: v, |, or · →: ->, => · ↔: <->, iff · ∀: forall, A · ∃: exists, E · ≤: <= · ≥: >= · ≠: !=. Use x^2 for a numeric power. Parentheses define scope.</p><p>T/true, F/false; y/yes, n/no. Laws: dm, dn, dist, comm, assoc, idem, identity, dom, abs, neg, 7.1, implication, contrapositive, biconditional. Rules: mp, mt, hs, ds, add, simp, conj, res; invalid/fallacy.</p>';
const dialog=document.querySelector('#shortcuts');document.querySelector('#help').onclick=()=>dialog.showModal();document.querySelector('#closeHelp').onclick=()=>dialog.close();
document.addEventListener('keydown',e=>{if(dialog.open)return;if(e.key==='Escape'){location.hash='home';return;}const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if(e.key==='?'&&!typing){dialog.showModal();return;}if(mode==='rapidfire'){onKey(e);return;}if(typing)return;if(mode==='home'&&/^[1-4]$/.test(e.key))location.hash=['flashcards','rapidfire','report','problems'][+e.key-1];else onKey(e);});
document.querySelector('#theme').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.settings.theme==='light');save();};
document.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='math381-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.querySelector('#import').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const s=JSON.parse(await f.text());const {validate}=await import('./store.js');validate(s);if(confirm('Replace current progress with this import?')){replace(s);document.body.classList.toggle('light',state.settings.theme==='light');route();}}catch(err){alert(err.message);}e.target.value='';};
document.querySelector('#reset').onclick=()=>{if(confirm('Erase all saved study progress? Export first if you want a backup.')){replace(fresh());document.body.classList.remove('light');route();}};
try{load();document.body.classList.toggle('light',state.settings.theme==='light');const names=['topics','flashcards','rapidfire','problems'];const values=await Promise.all(names.map(async n=>{const r=await fetch('content/'+n+'.json');if(!r.ok)throw Error(n+' could not be loaded');return r.json();}));data=Object.fromEntries(names.map((n,i)=>[n,values[i]]));addEventListener('hashchange',route);route();}catch(e){app.innerHTML='<h1>Could not open the study desk</h1><p class="error">'+esc(e.message)+'</p><p>Run <code>python3 -m http.server 8000</code> in the workspace and open <a href="http://localhost:8000">localhost:8000</a>. If saved progress is corrupt, export a backup from browser storage before using Reset.</p>';}
