import {parse,evaluate,methodCanonical} from './normalize.js';
export const pick=a=>a[Math.floor(Math.random()*a.length)];const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};const int=n=>Math.floor(Math.random()*n);
export const laws=[['dm','¬(p ∧ q) ≡ ¬p ∨ ¬q'],['dm','¬(p ∨ q) ≡ ¬p ∧ ¬q'],['dn','¬¬p ≡ p'],['dist','p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)'],['comm','p ∨ q ≡ q ∨ p'],['assoc','p ∧ (q ∧ r) ≡ (p ∧ q) ∧ r'],['idem','p ∨ p ≡ p'],['identity','p ∧ T ≡ p'],['dom','p ∨ T ≡ T'],['abs','p ∨ (p ∧ q) ≡ p'],['neg','p ∨ ¬p ≡ T'],['implication','p → q ≡ ¬p ∨ q'],['contrapositive','p → q ≡ ¬q → ¬p'],['biconditional','p ↔ q ≡ (p → q) ∧ (q → p)']];
export const names={mp:'Modus ponens',mt:'Modus tollens',hs:'Hypothetical syllogism',ds:'Disjunctive syllogism',add:'Addition',simp:'Simplification',conj:'Conjunction',res:'Resolution',invalid:'Invalid (a fallacy)',dm:'De Morgan',dn:'Double negation',dist:'Distributive',comm:'Commutative',assoc:'Associative',idem:'Idempotent',identity:'Identity',dom:'Domination',abs:'Absorption',neg:'Negation law',implication:'Conditional-disjunction (7.1)',contrapositive:'Contrapositive',biconditional:'Biconditional definition'};
export const full=k=>names[k]?(names[k].toLowerCase()===k?names[k]:names[k]+' ('+k+')'):k;
export const rules=[['mp','p → q; p ∴ q'],['mt','p → q; ¬q ∴ ¬p'],['hs','p → q; q → r ∴ p → r'],['ds','p ∨ q; ¬p ∴ q'],['add','p ∴ p ∨ q'],['simp','p ∧ q ∴ p'],['conj','p; q ∴ p ∧ q'],['res','p ∨ q; ¬p ∨ r ∴ q ∨ r'],['invalid','p → q; q ∴ p'],['invalid','p → q; ¬p ∴ ¬q']];
export function argument(s){const [prem,concl]=s.split(' ∴ ');return prem.split('; ').join('\n')+'\n∴ '+concl;}
function rename(s){const vars=pick([['p','q','r'],['a','b','c'],['r','s','t'],['(p ∧ q)','r','s']]);return s.replace(/[pqr]/g,c=>vars['pqr'.indexOf(c)]);}
function item(cat,topic,prompt,answer,explanation,type='text',display){return {id:'rf-'+cat+'-'+Math.random().toString(36).slice(2),cat,topic,prompt,answer,explanation,type,display:display||answer};}
// Print a propositional tree with only the parentheses a reader needs: none around the whole
// expression or a negated variable, and none inside a chain of the same ∧ or ∨.
export function show(t,parent){if(t.a)return t.a;if(t.n)return '¬'+(t.n.a?show(t.n):'('+show(t.n)+')');const s=show(t.l,t.o)+' '+t.o+' '+show(t.r,t.o);return parent&&!(parent===t.o&&(t.o==='∧'||t.o==='∨'))?'('+s+')':s;}

// ---- Proof-method identification ----
export const methodNames={direct:'Direct proof',contraposition:'Contraposition','contradiction':'Contradiction (of a proposition)','contradiction-implication':'Contradiction of an implication',biconditional:'Biconditional (both directions)',tfae:'TFAE cycle',counterexample:'Counterexample (disprove)'};
export let methodBank=[];export function setMethodBank(b){methodBank=b||[];}
export function methodItem(prompt,accepted,why){const it=item('method','1.7-choosing-a-method',prompt,accepted[0],why,'method',accepted.map(a=>methodNames[a]).join(' or '));it.accepted=accepted;return it;}
// Numbers a + b√2 with rational a, b: exact rational/irrational bookkeeping for verifying claims.
const Q={add:(x,y)=>[x[0]+y[0],x[1]+y[1]],sub:(x,y)=>[x[0]-y[0],x[1]-y[1]],mul:(x,y)=>[x[0]*y[0]+2*x[1]*y[1],x[0]*y[1]+x[1]*y[0]],rat:x=>x[1]===0};
const rationals=[[-2,0],[-1,0],[-.5,0],[.5,0],[1,0],[2,0],[3,0]],nzRationals=rationals,irrationals=[[0,1],[0,-1],[1,1],[-1,1],[0,2],[2,-1],[.5,1]];
const realSets={'rational':{name:'rational',pick:rationals,test:Q.rat},'nonzero rational':{name:'nonzero rational',pick:nzRationals,test:x=>Q.rat(x)&&x[0]!==0},'irrational':{name:'irrational',pick:irrationals,test:x=>!Q.rat(x)}};
const realOps={sum:['sum','x + y',Q.add],difference:['difference','x − y',Q.sub],product:['product','xy',Q.mul]};
const parity={even:n=>n%2===0,odd:n=>n%2!==0},ints=[0,1,2,3,4,5,6,7,8,9];
const intOps={sum:['sum','m + n',(a,b)=>a+b],product:['product','mn',(a,b)=>a*b],difference:['difference','m − n',(a,b)=>a-b]};
const every=(xs,ys,f)=>xs.every(x=>ys.every(y=>f(x,y)));
// Each template returns null when the claim cannot be verified or is not shaped as intended.
const templates=[
 function realClaim(){const [s1,s2]=[pick(Object.keys(realSets)),pick(Object.keys(realSets))],op=pick(Object.keys(realOps)),c=pick(['rational','irrational']);const S1=realSets[s1],S2=realSets[s2],[opName,expr,f]=realOps[op];const truth=every(S1.pick,S2.pick,(x,y)=>realSets[c].test(f(x,y)));if(s1!=='irrational'&&s2!=='irrational'&&c==='irrational')return null;const art=s=>s[0]==='i'?'an':'a';const claim=`the ${opName} of ${art(s1)} ${s1} number and ${art(s2)} ${s2} number is ${c}`;if(!truth)return methodItem(`Prove or disprove: ${claim}.`,['counterexample'],`Test examples: ${s1==='irrational'||s2==='irrational'?'use √2 and −√2 or √2 · √2 = 2':'try small fractions'}; the statement is false, so give a counterexample.`);const neg=c==='irrational';if(!neg&&s1!=='irrational'&&s2!=='irrational')return methodItem(pick([`If x is ${s1} and y is ${s2}, then ${expr} is ${c}.`,`Prove or disprove: ${claim}.`]),['direct'],'Both hypotheses unpack as fractions and the conclusion is positive: compute directly.');if(neg&&(s1==='irrational')!==(s2==='irrational'))return methodItem(pick([`If x is ${s1} and y is ${s2}, then ${expr} is ${c}.`,`Prove or disprove: ${claim}.`]),['contradiction-implication'],'If-then with a negative conclusion; contraposing still leaves irrationality to unpack. Assume the hypotheses and that the result is rational, then solve for the irrational one.');return null;},
 function intClaim(){const [p1,p2]=[pick(['even','odd']),pick(['even','odd'])],op=pick(Object.keys(intOps)),c=pick(['even','odd']),[opName,expr,f]=intOps[op];const A=ints.filter(parity[p1]),B=ints.filter(parity[p2]);const truth=every(A,B,(a,b)=>parity[c](f(a,b)));const claim=`the ${opName} of an ${p1} integer and an ${p2} integer is ${c}`;if(p1===p2&&op!=='product'&&c==='odd')return null;if(!truth)return methodItem(`Prove or disprove: ${claim}.`,['counterexample'],'Try m = 1, n = 2 or m = n = 1; the statement fails, so exhibit the counterexample.');return methodItem(pick([`If m is ${p1} and n is ${p2}, then ${expr} is ${c}.`,`Prove or disprove: ${claim}.`]),['direct'],'Both hypotheses unpack (m = 2k or 2k + 1) and the conclusion is positive: compute directly.');},
 function linear(){const a=pick([3,5,7,9]),b=pick([1,2,3,4,5,6]),hp=pick(['even','odd']);const ns=ints.filter(n=>parity[hp](a*n+b));if(!ns.length)return null;const cp=parity.even(ns[0])?'even':'odd';if(!ns.every(parity[cp]))return null;const kind=pick(['if','iff','tfae']);if(kind==='if')return methodItem(`If n is an integer and ${a}n + ${b} is ${hp}, then n is ${cp}.`,['contraposition'],`The hypothesis is about ${a}n + ${b}, which you cannot unpack; the negated conclusion “n is ${cp==='even'?'odd':'even'}” unpacks to n = 2k${cp==='even'?' + 1':''} at once.`);if(kind==='iff')return methodItem(`An integer n is ${cp} if and only if ${a}n + ${b} is ${hp}.`,['biconditional'],'“If and only if”: prove (→) directly and (←) by contraposition.');const sq=cp;return methodItem(`Show that for an integer n these are equivalent: (i) n is ${cp}; (ii) ${a}n + ${b} is ${hp}; (iii) n² is ${sq}.`,['tfae'],'Three statements to be shown equivalent: prove the cycle (i) → (ii) → (iii) → (i).');},
 function square(){const p=pick(['even','odd']);return methodItem(pick([`If n is an integer and n² is ${p}, then n is ${p}.`,`Prove or disprove: if n is an integer and n² is ${p}, then n is ${p}.`]),['contraposition','contradiction'],`n² ${p} does not unpack to anything about n; “n is ${p==='even'?'odd':'even'}” unpacks and squares to a${p==='even'?'n odd':'n even'} number.`);},
 function root(){const k=pick([2,3,5,6,7,8,10,11,12,13]);if(Number.isInteger(Math.sqrt(k)))return null;return methodItem(`√${k} is irrational.`,['contradiction'],`A bare negative claim, not an if-then: assume √${k} = p/q in lowest terms and derive that a prime factor divides both p and q.`);},
 function none(){return methodItem(pick(['There is no largest even integer.','There is no smallest positive rational number.','There is no largest multiple of 3.','There is no rational number whose square is 2.']),['contradiction'],'“There is no …” is a negative existence claim: assume such an object exists and produce a contradiction.');},
 function orConclusion(){const a=pick([2,3,4]),t=pick([[`x + y ≥ ${2*a}`,`x ≥ ${a} or y ≥ ${a}`],[`x + y > ${2*a}`,`x > ${a} or y > ${a}`],['mn is even','m is even or n is even'],['xy = 0','x = 0 or y = 0']]);return methodItem(`If ${t[0]}, then ${t[1]}.`,['contraposition'],'The conclusion is an “or”; negating it gives an “and” you can use directly.');},
];
export function methodGenerate(){for(let k=0;k<20;k++){const it=pick(templates)();if(it)return it;}return null;}
export const ruleTautologies={mp:'(p ∧ (p → q)) → q',mt:'(¬q ∧ (p → q)) → ¬p',hs:'((p → q) ∧ (q → r)) → (p → r)',ds:'((p ∨ q) ∧ ¬p) → q',add:'p → (p ∨ q)',simp:'(p ∧ q) → p',conj:'((p) ∧ (q)) → (p ∧ q)',res:'((p ∨ q) ∧ (¬p ∨ r)) → (q ∨ r)'};
const fallacyNames={'p → q; q ∴ p':'Affirming the conclusion (fallacy)','p → q; ¬p ∴ ¬q':'Denying the hypothesis (fallacy)'};
export const ruleChoiceNames=[...['mp','mt','hs','ds','add','simp','conj','res'].map(k=>names[k]),...Object.values(fallacyNames)];
export const generators={
 truth(){const vars=Math.random()<.25?['p','q','r']:['p','q'];const env=Object.fromEntries(vars.map(v=>[v,!!int(2)]));const e=show(tree(3,true)),answer=evaluate(parse(e),env)?'T':'F';return item('truth','1.1-conditional',Object.entries(env).map(([k,v])=>k+' = '+(v?'T':'F')).join(', ')+'\nEvaluate '+e,answer,'Evaluate the innermost parentheses first; → is false only for T → F. The result is '+answer+'.');
  function tree(d,root){if(!root&&(!d||Math.random()<.25))return {a:pick(vars)};if(!root&&Math.random()<.2)return {n:tree(d-1)};let node;for(let k=0;k<8;k++){let l=tree(d-1),r=tree(d-1);if(l.a&&r.a&&l.a===r.a)r={a:pick(vars.filter(v=>v!==l.a))};node={o:pick(['∧','∨','→','↔','⊕']),l,r};if(!/(?<![¬a-z])([a-z]) [∧∨→↔⊕] \1\b/.test(show(node)))break;}return node;}},
 law(){const [a,e]=pick(laws);return item('law','1.3-'+({dm:'demorgan',implication:'allowed',contrapositive:'allowed',biconditional:'allowed'}[a]||a),'Name the law: '+rename(e),a,'Match the connective pattern: '+full(a)+'.','text',full(a));},
 rule(){const [a,e]=pick(rules);return item('rule','1.6-'+(a==='invalid'?'fallacies':a),'Name the rule:\n'+argument(rename(e)),a,a==='invalid'?'p = F, q = T gives true premises and a false conclusion.':'This is the '+names[a].toLowerCase()+' pattern.','text',full(a));},
 validity(){const [a,e]=pick(rules);return item('validity','1.6-validity','Valid or invalid?\n'+argument(rename(e)),a==='invalid'?'invalid':'valid',a==='invalid'?'Counterexample: p = F, q = T.':'An instance of '+names[a].toLowerCase()+'; true premises force the conclusion.');},
 converse(){const [kind,a]=pick([['converse','q → p'],['inverse','¬p → ¬q'],['contrapositive','¬q → ¬p']]);return item('converse','1.1-'+kind,'Give the '+kind+' of p → q.',a,'Converse swaps; inverse negates; contrapositive does both.','symbolic');},
 negate(){const n=int(8),nest=!!int(2),q=pick(['∀','∃']),r=pick(['∀','∃']),flip=x=>x==='∀'?'∃':'∀',rel=nest?pick([['x + y = '+n,'x + y ≠ '+n],['x < y','x ≥ y']]):pick([['x > '+n,'x ≤ '+n],['x^2 = '+n,'x^2 ≠ '+n]]);return item('negate',nest?'1.5-negating':'1.4-negating','Negate: '+q+'x '+(nest?r+'y ':'')+'('+rel[0]+')',flip(q)+'x '+(nest?flip(r)+'y ':'')+'('+rel[1]+')','Flip every quantifier and negate the innermost relation.','symbolic');},
 quantifier(){const rel=pick(['x + y = 0','x*y = 1','x < y']),domain=pick(['ℝ','ℤ','ℕ','ℤ⁺']),nest=int(4),forms=['∀x∀y','∀x∃y','∃x∀y','∃x∃y'];let values,why;if(rel==='x + y = 0'){values=domain==='ℤ⁺'?[false,false,false,false]:domain==='ℕ'?[false,false,false,true]:[false,true,false,true];why=domain==='ℤ⁺'?'Positive integers cannot sum to zero.':domain==='ℕ'?'Only x=y=0 works; x=1 has no natural additive inverse.':'Choose y=−x for ∀∃; no fixed x works for every y. The pair (0,0) works for ∃∃.';}else if(rel==='x*y = 1'){values=[false,false,false,true];why='The pair (1,1) works. For ∀∃ use x=0 as a counterexample when available; over ℤ⁺ use x=2. No fixed x multiplies every y to 1.';}else{values=[false,true,domain==='ℕ'||domain==='ℤ⁺'?false:false,true];why='Choose y=x+1 for ∀∃. No x is less than every y (take y=x). A pair such as (1,2) establishes ∃∃.';}if(Math.random()<.2){const n=int(4),v=[false,true,false,true][n];return item('quantifier','1.5-nests',`Over ℝ: ${['∀x∀y∀z','∀x∀y∃z','∃z∀x∀y','∃x∃y∃z'][n]} (x + y = z)`,v?'T':'F','z=x+y can depend on x,y. One fixed z cannot equal every sum; 0+0=0 supplies witnesses.');}return item('quantifier','1.5-nests','Over '+domain+': '+forms[nest]+' ('+rel+')',values[nest]?'T':'F',why);},
 sets(){const n=int(7),k=int(5);if(k===0)return item('sets','2.1-power',`If |S| = ${n}, what is |P(S)|?`,String(2**n),'Each of the '+n+' elements can be included or omitted: 2^'+n+'.');if(k===1)return item('sets','2.1-cardinality',pick(['How many elements in {∅, {∅}, ∅}?','How many elements in {{1}, 1, {1}}?','How many elements in P(P(∅))?']),'2','Count distinct outermost elements; P(P(∅)) = {∅, {∅}}.');if(k===2)return item('sets','2.1-subset',`Is {${n}} ⊆ {${n}, ${n+1}}?`,'yes','Its only element is in the second set.');if(k===3)return item('sets','2.1-nested',`Is ${n} ∈ {{${n}}}?`,'no','The only element is the set {'+n+'}, not the number '+n+'.');return item('sets','2.1-equality',`Are {${n}, ${n+1}, ${n}} and {${n+1}, ${n}} equal?`,'yes','Order and duplicates do not affect a set.');},
 english(){const p=pick(['q unless ¬p','p only if q','q is necessary for p','p is sufficient for q','q whenever p','q if p']);return item('english','1.1-conditional','Translate: '+p,'p → q','p is the sufficient condition; q is the necessary result.','symbolic');},
 method(){if(methodBank.length&&Math.random()<.55){const b=pick(methodBank);return methodItem(b.prompt,b.accepted,b.why);}return methodGenerate()||methodItem(pick(methodBank).prompt,pick(methodBank).accepted,'');},
 rulematch(){const [a,e]=pick(rules),name=a==='invalid'?fallacyNames[e]:names[a],taut=a!=='invalid'&&Math.random()<.3;const prompt=taut?'Which rule has this tautology?\n'+rename(ruleTautologies[a]):'Which rule is this?\n'+argument(rename(e));const others=[];for(const n of shuffle(ruleChoiceNames.filter(n=>n!==name)))if(others.length<3)others.push(n);const it=item('rulematch','1.6-'+(a==='invalid'?'fallacies':a),prompt,name,a==='invalid'?'Invalid: p = F, q = T makes the premises true and the conclusion false.':'Rosen §1.6 Table 1: '+name.toLowerCase()+' is '+ruleTautologies[a]+'.','choice',name);it.choices=shuffle([name,...others]);return it;},
 definition(){const a=pick([['An integer n is odd iff n = ___ for some k ∈ ℤ.','2k+1','1.7-odd'],['An integer n is even iff n = ___ for some k ∈ ℤ.','2k','1.7-even'],['An integer n is a perfect square iff n = ___ for some k ∈ ℤ.','k^2','1.7-square'],['An always-true compound proposition is a ___.','tautology','1.3-tautology'],['The set with no elements is the ___ set.','empty','2.1-empty']]);return item('definition',a[2],a[0],a[1],'Apply the definition, including the integer/domain condition.',a[1].includes('k')?'symbolic':'text');}
};
