import {parse,evaluate} from './normalize.js';
export const pick=a=>a[Math.floor(Math.random()*a.length)];const int=n=>Math.floor(Math.random()*n);
export const laws=[['dm','¬(p ∧ q) ≡ ¬p ∨ ¬q'],['dm','¬(p ∨ q) ≡ ¬p ∧ ¬q'],['dn','¬¬p ≡ p'],['dist','p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)'],['comm','p ∨ q ≡ q ∨ p'],['assoc','p ∧ (q ∧ r) ≡ (p ∧ q) ∧ r'],['idem','p ∨ p ≡ p'],['identity','p ∧ T ≡ p'],['dom','p ∨ T ≡ T'],['abs','p ∨ (p ∧ q) ≡ p'],['neg','p ∨ ¬p ≡ T'],['implication','p → q ≡ ¬p ∨ q'],['contrapositive','p → q ≡ ¬q → ¬p'],['biconditional','p ↔ q ≡ (p → q) ∧ (q → p)']];
export const rules=[['mp','p → q; p ∴ q'],['mt','p → q; ¬q ∴ ¬p'],['hs','p → q; q → r ∴ p → r'],['ds','p ∨ q; ¬p ∴ q'],['add','p ∴ p ∨ q'],['simp','p ∧ q ∴ p'],['conj','p; q ∴ p ∧ q'],['res','p ∨ q; ¬p ∨ r ∴ q ∨ r'],['invalid','p → q; q ∴ p'],['invalid','p → q; ¬p ∴ ¬q']];
function rename(s){const vars=pick([['p','q','r'],['a','b','c'],['r','s','t'],['(p ∧ q)','r','s']]);return s.replace(/[pqr]/g,c=>vars['pqr'.indexOf(c)]);}
function item(cat,topic,prompt,answer,explanation,type='text'){return {id:'rf-'+cat+'-'+Math.random().toString(36).slice(2),cat,topic,prompt,answer,explanation,type};}
export const generators={
 truth(){const vars=Math.random()<.25?['p','q','r']:['p','q'];const env=Object.fromEntries(vars.map(v=>[v,!!int(2)]));function expr(depth){if(!depth||Math.random()<.25)return pick(vars);if(Math.random()<.2)return '¬('+expr(depth-1)+')';return '('+expr(depth-1)+' '+pick(['∧','∨','→','↔','⊕'])+' '+expr(depth-1)+')';}const e=expr(3),answer=evaluate(parse(e),env)?'T':'F';return item('truth','1.1-conditional',Object.entries(env).map(([k,v])=>k+' = '+(v?'T':'F')).join(', ')+'\nEvaluate '+e,answer,'Evaluate parentheses first; → is false only for T → F. The result is '+answer+'.');},
 law(){const [a,e]=pick(laws);return item('law','1.3-'+({dm:'demorgan',implication:'allowed',contrapositive:'allowed',biconditional:'allowed'}[a]||a),'Name the law: '+rename(e),a,'Match the connective pattern: '+a+'.');},
 rule(){const [a,e]=pick(rules);return item('rule','1.6-'+(a==='invalid'?'fallacies':a),'Name the rule: '+rename(e),a,a==='invalid'?'p = F, q = T gives true premises and a false conclusion.':'This is the '+a+' inference pattern.');},
 validity(){const [a,e]=pick(rules);return item('validity','1.6-validity','Valid or invalid? '+rename(e),a==='invalid'?'invalid':'valid',a==='invalid'?'Counterexample: p = F, q = T.':'An instance of '+a+'; true premises force the conclusion.');},
 converse(){const [kind,a]=pick([['converse','q → p'],['inverse','¬p → ¬q'],['contrapositive','¬q → ¬p']]);return item('converse','1.1-'+kind,'Give the '+kind+' of p → q.',a,'Converse swaps; inverse negates; contrapositive does both.','symbolic');},
 negate(){const n=int(8),nest=!!int(2),q=pick(['∀','∃']),r=pick(['∀','∃']),flip=x=>x==='∀'?'∃':'∀',rel=nest?pick([['x + y = '+n,'x + y ≠ '+n],['x < y','x ≥ y']]):pick([['x > '+n,'x ≤ '+n],['x^2 = '+n,'x^2 ≠ '+n]]);return item('negate',nest?'1.5-negating':'1.4-negating','Negate: '+q+'x '+(nest?r+'y ':'')+'('+rel[0]+')',flip(q)+'x '+(nest?flip(r)+'y ':'')+'('+rel[1]+')','Flip every quantifier and negate the innermost relation.','symbolic');},
 quantifier(){const rel=pick(['x + y = 0','x*y = 1','x < y']),domain=pick(['ℝ','ℤ','ℕ','ℤ⁺']),nest=int(4),forms=['∀x∀y','∀x∃y','∃x∀y','∃x∃y'];let values,why;if(rel==='x + y = 0'){values=domain==='ℤ⁺'?[false,false,false,false]:domain==='ℕ'?[false,false,false,true]:[false,true,false,true];why=domain==='ℤ⁺'?'Positive integers cannot sum to zero.':domain==='ℕ'?'Only x=y=0 works; x=1 has no natural additive inverse.':'Choose y=−x for ∀∃; no fixed x works for every y. The pair (0,0) works for ∃∃.';}else if(rel==='x*y = 1'){values=[false,false,false,true];why='The pair (1,1) works. For ∀∃ use x=0 as a counterexample when available; over ℤ⁺ use x=2. No fixed x multiplies every y to 1.';}else{values=[false,true,domain==='ℕ'||domain==='ℤ⁺'?false:false,true];why='Choose y=x+1 for ∀∃. No x is less than every y (take y=x). A pair such as (1,2) establishes ∃∃.';}if(Math.random()<.2){const n=int(4),v=[false,true,false,true][n];return item('quantifier','1.5-nests',`Over ℝ: ${['∀x∀y∀z','∀x∀y∃z','∃z∀x∀y','∃x∃y∃z'][n]} (x + y = z)`,v?'T':'F','z=x+y can depend on x,y. One fixed z cannot equal every sum; 0+0=0 supplies witnesses.');}return item('quantifier','1.5-nests','Over '+domain+': '+forms[nest]+' ('+rel+')',values[nest]?'T':'F',why);},
 sets(){const n=int(7),k=int(5);if(k===0)return item('sets','2.1-power',`If |S| = ${n}, what is |P(S)|?`,String(2**n),'Each of the '+n+' elements can be included or omitted: 2^'+n+'.');if(k===1)return item('sets','2.1-cardinality',pick(['How many elements in {∅, {∅}, ∅}?','How many elements in {{1}, 1, {1}}?','How many elements in P(P(∅))?']),'2','Count distinct outermost elements; P(P(∅)) = {∅, {∅}}.');if(k===2)return item('sets','2.1-subset',`Is {${n}} ⊆ {${n}, ${n+1}}?`,'yes','Its only element is in the second set.');if(k===3)return item('sets','2.1-nested',`Is ${n} ∈ {{${n}}}?`,'no','The only element is the set {'+n+'}, not the number '+n+'.');return item('sets','2.1-equality',`Are {${n}, ${n+1}, ${n}} and {${n+1}, ${n}} equal?`,'yes','Order and duplicates do not affect a set.');},
 english(){const p=pick(['q unless ¬p','p only if q','q is necessary for p','p is sufficient for q','q whenever p','q if p']);return item('english','1.1-conditional','Translate: '+p,'p → q','p is the sufficient condition; q is the necessary result.','symbolic');},
 definition(){const a=pick([['An integer n is odd iff n = ___ for some k ∈ ℤ.','2k+1','1.7-odd'],['An integer n is even iff n = ___ for some k ∈ ℤ.','2k','1.7-even'],['An integer n is a perfect square iff n = ___ for some k ∈ ℤ.','k^2','1.7-square'],['An always-true compound proposition is a ___.','tautology','1.3-tautology'],['The set with no elements is the ___ set.','empty','2.1-empty']]);return item('definition',a[2],a[0],a[1],'Apply the definition, including the integer/domain condition.',a[1].includes('k')?'symbolic':'text');}
};
