// Recursive-descent parser. Logical structure is preserved; only AND/OR
// associativity and commutativity are canonicalized, never implication direction.
export function symbols(s){return s.replace(/²/g,'^2').replace(/³/g,'^3').normalize('NFKC').replace(/\bforall\b/gi,'∀').replace(/\bexists\b/gi,'∃').replace(/\bA(?=\s*[a-z](?![a-z_0-9]))/g,'∀').replace(/\bE(?=\s*[a-z](?![a-z_0-9]))/g,'∃').replace(/([∀∃])\s*([A-Za-z])(?=[A-Za-z])/g,'$1$2 ').toLowerCase().replace(/<->|\biff\b/g,'↔').replace(/->|=>/g,'→').replace(/!=/g,'≠').replace(/<=/g,'≤').replace(/>=/g,'≥').replace(/\bnot\b|[~!]/g,'¬').replace(/\band\b|&/g,'∧').replace(/\bor\b|\bv\b|\|/g,'∨').replace(/\bxor\b/g,'⊕').replace(/\^(?!\s*\d)/g,'∧').replace(/−/g,'-').replace(/[·×]/g,'*').replace(/\btrue\b/g,'t').replace(/\bfalse\b/g,'f').replace(/\s+/g,' ').trim();}
export function parse(input){const s=symbols(input),tokens=s.match(/∀|∃|¬|∧|∨|⊕|→|↔|≤|≥|≠|[(){}\[\],+*/^=<>-]|[a-z_][a-z_0-9]*|\d+(?:\.\d+)?/g)||[];if(tokens.join('')!==s.replace(/\s/g,''))throw Error('Unknown symbol');let i=0;const peek=()=>tokens[i],take=()=>tokens[i++],need=t=>{if(take()!==t)throw Error('Expected '+t);};
 const bin=(next,ops)=>{let a=next();while(ops.includes(peek()))a={op:take(),args:[a,next()]};return a;};
 function atom(){let t=take();if(!t)throw Error('Incomplete answer');if(t==='('||t==='['){let a=iff();need(t==='('?')':']');return a;}if(t==='-')return {op:'negative',args:[atom()]};if(!/^[a-z_0-9]/.test(t))throw Error('Expected variable or number');if(peek()==='('){take();const args=[iff()];while(peek()===','){take();args.push(iff());}need(')');return {op:'call:'+t,args};}return {op:'atom',value:t};}
 const power=()=>bin(atom,['^']);
 function product(){let a=power();while(peek()==='*'||peek()==='/'||/^[a-z_0-9]/.test(peek()||'')){const op=['*','/'].includes(peek())?take():'*';a={op,args:[a,power()]};}return a;}
 const sum=()=>bin(product,['+','-']);
 const relation=()=>bin(sum,['=','≠','<','>','≤','≥']);
 function unary(){if(peek()==='¬'){take();return {op:'¬',args:[unary()]};}if(peek()==='∀'||peek()==='∃'){const op=take(),v=take();if(!/^[a-z]$/.test(v||''))throw Error('Quantifier needs a variable');return {op,variable:v,args:[unary()]};}return relation();}
 const and=()=>bin(unary,['∧']);const or=()=>bin(and,['∨','⊕']);
 function implication(){let a=or();if(peek()==='→'){take();a={op:'→',args:[a,implication()]};}return a;}
 const iff=()=>bin(implication,['↔']);const ast=iff();if(i!==tokens.length)throw Error('Trailing input');return ast;}
export function canonical(n){if(n.op==='atom')return n.value;let args=n.args||[];if(n.op==='∧'||n.op==='∨'){const flatten=x=>x.op===n.op?x.args.flatMap(flatten):[x];args=args.flatMap(flatten);return n.op+'('+args.map(canonical).sort().join(',')+')';}return n.op+(n.variable||'')+'('+args.map(canonical).join(',')+')';}
const aliases={dm:['demorgan','demorgans','dm'],dn:['dn','doublenegation'],dist:['dist','distributive','distributivity'],comm:['comm','commutative','commutativity'],assoc:['assoc','associative','associativity'],idem:['idem','idempotent','idempotence'],identity:['identity'],dom:['dom','domination'],abs:['abs','absorption'],neg:['neg','negation'],implication:['7.1','conditionaldisjunction','implication'],contrapositive:['contrapositive','contraposition'],biconditional:['biconditional'],mp:['mp','modusponens'],mt:['mt','modustollens'],hs:['hs','hypotheticalsyllogism'],ds:['ds','disjunctivesyllogism'],add:['add','addition'],simp:['simp','simplification'],conj:['conj','conjunction'],res:['res','resolution'],invalid:['invalid','fallacy','affirmingtheconclusion','denyingthehypothesis'],t:['t','true'],f:['f','false'],yes:['y','yes'],no:['n','no']};
export function textCanonical(s){const x=s.toLowerCase().replace(/[\s’'\-]/g,'');return Object.keys(aliases).find(k=>aliases[k].includes(x))||x;}
export const methodAliases={direct:['direct','directproof','d'],contraposition:['contraposition','contrapositive','cp','contra','bycontraposition'],contradiction:['contradiction','contradictionofaproposition','bwoc','bycontradiction','cd'],'contradiction-implication':['contradictionimplication','contradictionofanimplication','contradictionofimplication','contradictionimpl','ci','assumepandnotq','assumepandnegq'],biconditional:['biconditional','iff','bothdirections','bi','ifandonlyif'],tfae:['tfae','cycle','equivalent','thefollowingareequivalent','equivalence'],counterexample:['counterexample','disprove','disproof','false','ce']};
export function methodCanonical(s){const x=String(s).toLowerCase().replace(/[\s’'\-.]/g,'');return Object.keys(methodAliases).find(k=>methodAliases[k].includes(x))||x;}
export function matches(given,expected,type='text'){if(!given.trim())return false;if(type==='method')return methodCanonical(given)===methodCanonical(expected);if(type==='symbolic'){try{return canonical(parse(given))===canonical(parse(expected));}catch{return false;}}return textCanonical(given)===textCanonical(expected);}
export function evaluate(n,env){const a=()=>evaluate(n.args[0],env),b=()=>evaluate(n.args[1],env);switch(n.op){case'atom':return n.value==='t'?true:n.value==='f'?false:env[n.value];case'¬':return !a();case'∧':return a()&&b();case'∨':return a()||b();case'⊕':return a()!==b();case'→':return !a()||b();case'↔':return a()===b();default:throw Error('Not propositional');}}
