import {app,data,register} from './app.js';import {state,save,median} from './store.js';import {esc} from './math.js';import {generators,pick} from './generators.js';import {matches} from './normalize.js';
const labels={truth:'Truth values',law:'Name the law',rule:'Name the rule',validity:'Valid or invalid',converse:'Converse / inverse / contrapositive',negate:'Negate it',quantifier:'Quantifier truth values',sets:'Sets',english:'English → symbols',definition:'Fill in definitions'};
export function setup(){app.innerHTML=`<div class="eyebrow">02 / Speed</div><h1>Make it automatic.</h1><p class="lead">Type the answer. Correct answers advance immediately. Press Enter to submit an answer that hasn’t matched.</p><div class="panel"><div class="toolbar"><label>Duration <select id="duration">${[60,120,180,0].map(n=>`<option value="${n}" ${state.settings.rfDuration===n?'selected':''}>${n||'∞'}${n?' seconds':''}</option>`).join('')}</select></label><label>Correction display <select id="delay">${[600,1200,2000].map(n=>`<option value="${n}" ${state.settings.rfWrongDelayMs===n?'selected':''}>${n/1000}s</option>`).join('')}</select></label></div><div class="checklist">${Object.entries(labels).map(([k,v])=>`<label><input type="checkbox" name="cat" value="${k}" checked> ${v}</label>`).join('')}</div><p><label><input id="weak" type="checkbox"> Weak topics only (accuracy below 70% or fewer than 3 attempts)</label></p><button class="primary" id="start">Start session</button></div>`;document.querySelector('#start').onclick=()=>{const cats=[...document.querySelectorAll('[name=cat]:checked')].map(c=>c.value);if(!cats.length){alert('Select at least one category.');return;}state.settings.rfDuration=+document.querySelector('#duration').value;state.settings.rfWrongDelayMs=+document.querySelector('#delay').value;save();run(cats,document.querySelector('#weak').checked);};register(()=>{});}
function run(cats,weak){let attempts=[],queue=[],current,start=Date.now(),shown=0,locked=false,ended=false,advanceTimer;const duration=state.settings.rfDuration;
 app.innerHTML='<div class="toolbar"><span class="eyebrow">02 / Rapid-fire</span><span id="score"></span><span id="timer"></span><button id="finish">End session</button></div><div class="meter"><span id="timebar"></span></div><div class="drill center"><small id="category"></small><h2 id="prompt" style="white-space:pre-line"></h2><input id="answer" autocomplete="off" spellcheck="false" aria-label="Your answer"><p id="feedback" aria-live="polite"></p><small>Correct → automatic · Enter → submit · ? in header → aliases</small></div>';
 const input=document.querySelector('#answer');
 const stats=topic=>{const a=state.rapidfire.attempts.filter(a=>a.topic===topic).slice(-20);return {n:a.length,acc:a.length?a.filter(a=>a.ok).length/a.length:0};};
 function next(){if(ended)return;locked=false;const retry=queue.findIndex(q=>q.after<=attempts.length);if(retry>=0)current=queue.splice(retry,1)[0].item;else{let candidates=Array.from({length:40},()=>generators[pick(cats)]());if(weak){const filtered=candidates.filter(c=>{const s=stats(c.topic);return s.n<3||s.acc<.7;});if(filtered.length)candidates=filtered;}const weights=candidates.map(c=>{const s=stats(c.topic);return 1+3*(1-s.acc)+2*(s.n<3);});let roll=Math.random()*weights.reduce((a,b)=>a+b,0),idx=0;while(idx<weights.length-1&&(roll-=weights[idx])>0)idx++;current=candidates[idx];}document.querySelector('#category').textContent=labels[current.cat];document.querySelector('#prompt').textContent=current.prompt;input.value='';input.disabled=false;input.classList.remove('bad');document.querySelector('#feedback').textContent='';shown=performance.now();input.focus();tick();}
 function answer(submit=false){if(locked||ended)return;if(duration&&Date.now()-start>=duration*1000){finish();return;}const ok=matches(input.value,current.answer,current.type);if(!ok&&!submit)return;locked=true;const a={t:Date.now(),item:current.id,cat:current.cat,topic:current.topic,ok,ms:Math.round(performance.now()-shown),given:input.value,expected:current.answer,prompt:current.prompt,explanation:current.explanation};attempts.push(a);state.rapidfire.attempts.push(a);save();if(ok){advanceTimer=setTimeout(next,70);}else{input.classList.add('bad');input.disabled=true;document.querySelector('#feedback').textContent=current.answer+' — '+current.explanation;queue.push({item:current,after:attempts.length+3});advanceTimer=setTimeout(next,state.settings.rfWrongDelayMs);}}
 function tick(){if(ended)return;const left=duration?Math.max(0,duration-(Date.now()-start)/1000):0;document.querySelector('#timer').textContent=duration?Math.ceil(left)+'s':'∞';document.querySelector('#score').textContent=attempts.filter(a=>a.ok).length+' correct / '+attempts.length;document.querySelector('#timebar').style.width=(duration?100*left/duration:100)+'%';if(duration&&left<=0)finish();}
 function finish(){if(ended)return;ended=true;clearInterval(timer);clearTimeout(advanceTimer);const score=attempts.filter(a=>a.ok).length;state.rapidfire.sessions.push({t:Date.now(),dur:duration,score,acc:attempts.length?score/attempts.length:0});save();results(attempts);}
 input.oninput=()=>answer(false);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();answer(true);}};document.querySelector('#finish').onclick=finish;const timer=setInterval(tick,100);register(e=>{if(e.key==='Escape'&&!ended){e.preventDefault();finish();}},()=>{if(!ended)finish();clearInterval(timer);clearTimeout(advanceTimer);});next();}
function results(attempts){const good=attempts.filter(a=>a.ok).length;app.innerHTML=`<div class="eyebrow">Session complete</div><h1>${good} correct.</h1><p>${attempts.length?Math.round(100*good/attempts.length):0}% accuracy · ${(median(attempts.map(a=>a.ms))/1000).toFixed(1)}s median response</p><button id="again" class="primary">Drill again</button><a href="#report"> Review weak topics →</a><h2>By category</h2>${summary(attempts,'cat')}<h2>By topic</h2>${summary(attempts,'topic')}<h2>Misses (${attempts.length-good})</h2>${attempts.filter(a=>!a.ok).map(a=>`<details class="panel"><summary style="white-space:pre-line">${esc(a.prompt)}</summary><p>Your answer: ${esc(a.given||'(blank)')}</p><p>Answer: ${esc(a.expected)}. ${esc(a.explanation)}</p><a href="#report/${encodeURIComponent(a.topic)}">Go to notes</a></details>`).join('')||'<p>No misses this session.</p>'}`;document.querySelector('#again').onclick=setup;}
function summary(attempts,key){return '<table><tr><th>'+key+'</th><th>Accuracy</th><th>Median</th></tr>'+[...new Set(attempts.map(a=>a[key]))].map(k=>{const a=attempts.filter(x=>x[key]===k);return `<tr><td>${esc(key==='cat'?labels[k]:data.topics.find(t=>t.id===k)?.title||k)}</td><td>${a.filter(x=>x.ok).length}/${a.length}</td><td>${(median(a.map(x=>x.ms))/1000).toFixed(1)}s</td></tr>`;}).join('')+'</table>';}
