import {app,data,register} from './app.js';import {state,save,median,missBank} from './store.js';import {esc} from './math.js';import {generators,pick,setMethodBank,methodNames,setRuleForm} from './generators.js';import {matches,methodCanonical} from './normalize.js';
import {shuffle} from './learn.js';
export const labels={truth:'Truth values',law:'Name the law',rule:'Name the rule',validity:'Valid or invalid',converse:'Converse / inverse / contrapositive',negate:'Negate it',quantifier:'Quantifier truth values',sets:'Sets',english:'English → symbols',definition:'Fill in definitions',method:'Which proof method?'};
const wrongOptions=[[0,'Pause until I continue'],[1200,'Show for 1.2s, then continue'],[2000,'Show for 2s, then continue'],[4000,'Show for 4s, then continue']];
export function setup(){setMethodBank(data.rapidfire.method);setRuleForm(state.settings.ruleForm||'book');const bank=missBank(state.rapidfire.attempts);app.innerHTML=`<div class="eyebrow">02 / Speed</div><h1>Make it automatic.</h1><p class="lead">Type the answer. Correct answers advance immediately. Press Enter to submit an answer that hasn’t matched.</p><div class="panel"><div class="toolbar"><label>Duration <select id="duration">${[60,120,180,0].map(n=>`<option value="${n}" ${state.settings.rfDuration===n?'selected':''}>${n||'∞'}${n?' seconds':''}</option>`).join('')}</select></label><label>Rules of inference <select id="ruleForm"><option value="book" ${(state.settings.ruleForm||'book')==='book'?'selected':''}>Exactly as in Table 1 (p, q, r)</option><option value="renamed" ${state.settings.ruleForm==='renamed'?'selected':''}>Renamed variables (harder)</option></select></label><label>Wrong answers <select id="delay">${wrongOptions.map(([n,l])=>`<option value="${n}" ${state.settings.rfWrongDelayMs===n?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="checklist">${Object.entries(labels).map(([k,v])=>`<label><input type="checkbox" name="cat" value="${k}" checked> ${v}</label>`).join('')}</div><p><label><input id="weak" type="checkbox"> Weak topics only (accuracy below 70% or fewer than 3 attempts)</label></p><p><label><input id="strict" type="checkbox" ${state.settings.strictContradiction?'checked':''}> Strict contradiction types (“contradiction” alone is not accepted for contradiction of an implication)</label></p><div class="toolbar"><button class="primary" id="start">Start session</button><button id="review" ${bank.length?'':'disabled'}>Review misses (${bank.length})</button><small class="muted">Misses stay in the bank until you answer them correctly.</small></div></div>`;
 const settings=()=>{state.settings.rfDuration=+document.querySelector('#duration').value;state.settings.rfWrongDelayMs=+document.querySelector('#delay').value;state.settings.strictContradiction=document.querySelector('#strict').checked;state.settings.ruleForm=document.querySelector('#ruleForm').value;setRuleForm(state.settings.ruleForm);save();};
 document.querySelector('#start').onclick=()=>{const cats=[...document.querySelectorAll('[name=cat]:checked')].map(c=>c.value);if(!cats.length){alert('Select at least one category.');return;}settings();run(cats,document.querySelector('#weak').checked);};
 document.querySelector('#review').onclick=()=>{settings();misses();};register(()=>{});}
let missIndex=0,missCat='';
function misses(){const all=missBank(state.rapidfire.attempts),cats=[...new Set(all.map(a=>a.cat))],list=all.filter(a=>!missCat||a.cat===missCat);if(!list.length){missCat='';if(!all.length){setup();return;}}
 missIndex=(missIndex+list.length)%(list.length||1);const m=list[missIndex];
 app.innerHTML=`<div class="eyebrow">02 / Rapid-fire · Misses</div><h1>Your miss bank</h1><div class="toolbar"><a href="#rapidfire" id="back">← Session setup</a><label>Category <select id="missCat"><option value="">All (${all.length})</option>${cats.map(c=>`<option value="${c}" ${c===missCat?'selected':''}>${labels[c]} (${all.filter(a=>a.cat===c).length})</option>`).join('')}</select></label><button class="primary" id="drill">Drill these ${list.length} misses</button></div>${m?`<p class="muted">${missIndex+1} / ${list.length} · ${esc(labels[m.cat])} · ${esc(data.topics.find(t=>t.id===m.topic)?.title||m.topic)} · missed ${new Date(m.t).toLocaleDateString()}</p><div class="panel miss"><h2 style="white-space:pre-line">${formatPrompt(m.prompt)}</h2><p class="error">Your answer: ${esc(m.given||'(blank)')}</p><p class="good"><strong>Answer: ${esc(m.expected)}</strong></p><p>${esc(m.explanation)}</p><a href="#report/${encodeURIComponent(m.topic)}">Go to notes →</a></div><div class="toolbar center mark"><button id="prev">← Previous</button><button id="next">Next →</button></div><p class="muted center">Arrow keys move between misses.</p>`:'<p>No misses in this category.</p>'}`;
 document.querySelector('#missCat').onchange=e=>{missCat=e.target.value;missIndex=0;misses();};document.querySelector('#drill').onclick=()=>run([],false,list);
 const move=n=>{missIndex+=n;misses();};if(m){document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);}
 register(e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);});}
// Prompt text -> HTML: assignment lines become chips, parentheses are colored by nesting depth.
export function formatPrompt(text){return text.split('\n').map(line=>{if(/^([a-z] = [TF])(, [a-z] = [TF])*$/.test(line))return '<span class="assign">'+line.split(', ').map(x=>'<span>'+esc(x)+'</span>').join('')+'</span>';if(line==='---')return '<span class="argline"></span>';let d=0;if(!/[()¬∧∨→↔⊕≡∀∃∴]/.test(line))return esc(line);return '<span class="formula">'+esc(line).replace(/[()]/g,c=>c==='('?`<span class="paren d${d++%4}">(</span>`:`<span class="paren d${--d%4}">)</span>`)+'</span>';}).join('\n');}
export const guessType=a=>a.type||(/[¬∧∨→↔∀∃≠≤≥^<>=+*]/.test(a.expected)?'symbolic':'text');
function run(cats,weak,pool){let attempts=[],queue=[],current,start=Date.now(),pausedMs=0,pauseStart=0,shown=0,locked=false,ended=false,advanceTimer;const duration=state.settings.rfDuration,pauseMode=state.settings.rfWrongDelayMs===0;
 const drill=pool?shuffle(pool).map(a=>({id:a.item,cat:a.cat,topic:a.topic,prompt:a.prompt,answer:a.key||a.expected,display:a.expected,explanation:a.explanation,type:a.accepted?'method':a.choices?'choice':guessType(a),accepted:a.accepted,choices:a.choices})):null;
 app.innerHTML=`<div class="toolbar"><span class="eyebrow">02 / Rapid-fire${drill?' · Misses':''}</span><span id="score"></span><span id="timer"></span><button id="finish">End session</button></div><div class="meter"><span id="timebar"></span></div><div class="drill center"><small id="category"></small><h2 id="prompt" style="white-space:pre-line"></h2><div class="choices" id="choices" hidden></div><input id="answer" autocomplete="off" spellcheck="false" aria-label="Your answer"><div class="toolbar symbols" id="symbols" aria-label="Insert a symbol">${['¬','∧','∨','⊕','→','↔','∀','∃','≠','≤','≥','∴'].map(x=>`<button type="button" data-sym="${x}" tabindex="-1">${x}</button>`).join('')}</div><div class="toolbar center"><button type="button" id="giveup" tabindex="-1">I don't know — show answer</button></div><p id="feedback" aria-live="polite"></p><div class="toolbar center" id="continueBar" hidden><button class="primary" id="continue">Continue (Enter)</button><a id="notes" href="#report">Go to notes →</a></div><small>Correct → automatic · Enter → submit · Enter on an empty box → I don't know · ? in header → aliases</small></div>`;
 const input=document.querySelector('#answer');document.querySelectorAll('#symbols button').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>{if(input.disabled)return;const [a,z]=[input.selectionStart??input.value.length,input.selectionEnd??input.value.length];input.setRangeText(b.dataset.sym,a,z,'end');input.focus();input.dispatchEvent(new Event('input'));};});
 const stats=topic=>{const a=state.rapidfire.attempts.filter(a=>a.topic===topic).slice(-20);return {n:a.length,acc:a.length?a.filter(a=>a.ok).length/a.length:0};};
 const elapsed=()=>Date.now()-start-pausedMs-(pauseStart?Date.now()-pauseStart:0);
 function next(){if(ended)return;clearTimeout(matchTimer);if(pauseStart){pausedMs+=Date.now()-pauseStart;pauseStart=0;}locked=false;const retry=queue.findIndex(q=>q.after<=attempts.length);if(retry>=0)current=queue.splice(retry,1)[0].item;else if(drill){if(!drill.length){if(queue.length)current=queue.shift().item;else{finish();return;}}else current=drill.shift();}else{let candidates=Array.from({length:40},()=>generators[pick(cats)]());if(weak){const filtered=candidates.filter(c=>{const s=stats(c.topic);return s.n<3||s.acc<.7;});if(filtered.length)candidates=filtered;}const weights=candidates.map(c=>{const s=stats(c.topic);return 1+3*(1-s.acc)+2*(s.n<3);});let roll=Math.random()*weights.reduce((a,b)=>a+b,0),idx=0;while(idx<weights.length-1&&(roll-=weights[idx])>0)idx++;current=candidates[idx];if(current.prompt===lastPrompt){const alt=candidates.find(c=>c.prompt!==lastPrompt);if(alt)current=alt;}}lastPrompt=current.prompt;document.querySelector('#category').textContent=labels[current.cat];document.querySelector('#prompt').innerHTML=formatPrompt(current.prompt);const ch=document.querySelector('#choices'),typed=!current.choices;ch.hidden=typed;input.hidden=!typed;document.querySelector('#symbols').hidden=!typed;giveup.hidden=!typed;if(!typed){ch.innerHTML=current.choices.map((c,k)=>`<button type="button" class="choice" data-k="${k}"><span class="num">${k+1}</span><div>${esc(c)}</div></button>`).join('');ch.querySelectorAll('.choice').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>choose(+b.dataset.k);});}input.value='';input.disabled=false;giveup.disabled=false;input.classList.remove('bad');document.querySelector('#feedback').textContent='';document.querySelector('#continueBar').hidden=true;shown=performance.now();if(typed)input.focus();else document.activeElement?.blur();tick();}
 function choose(k){if(locked||ended||!current.choices)return;const c=current.choices[k];if(c===undefined)return;input.value=c;document.querySelectorAll('#choices .choice').forEach((b,i)=>{b.disabled=true;if(current.choices[i]===current.answer)b.classList.add('right');else if(i===k)b.classList.add('wrong');});answer(true);}
 let matchTimer,lastPrompt='';
 function answer(submit=false,fromTimer=false){if(locked||ended)return;if(duration&&elapsed()>=duration*1000){finish();return;}let ok,note='';if(current.accepted){const g=methodCanonical(input.value),acc=current.accepted,idx=acc.indexOf(g),strict=state.settings.strictContradiction;if(idx>0){ok=true;note='Accepted. Best method here: '+methodNames[acc[0]]+'.';}else if(idx===0)ok=true;else if(!strict&&g==='contradiction'&&acc.includes('contradiction-implication')){ok=true;note='Accepted as contradiction; specifically this is contradiction of an implication (assume p and ¬q).';}else if(!strict&&g==='contradiction-implication'&&acc.includes('contradiction')){ok=true;note='Accepted; this one is a bare claim, so plain contradiction of a proposition.';}else ok=false;}else if(current.choices)ok=input.value===current.answer;else ok=matches(input.value,current.answer,current.type);if(!ok&&(!submit||fromTimer))return;if(ok&&!submit){clearTimeout(matchTimer);matchTimer=setTimeout(()=>answer(true,true),400);return;}clearTimeout(matchTimer);locked=true;const a={note,accepted:current.accepted,choices:current.choices,why:current.accepted?current.explanation:undefined,t:Date.now(),item:current.id,cat:current.cat,topic:current.topic,ok,ms:Math.round(performance.now()-shown),given:input.value.trim()||'(I don\'t know)',expected:current.display||current.answer,key:current.answer,prompt:current.prompt,explanation:current.explanation,type:current.type};attempts.push(a);state.rapidfire.attempts.push(a);save();if(ok){advanceTimer=setTimeout(next,70);}else{input.classList.add('bad');input.disabled=true;giveup.disabled=true;document.querySelector('#feedback').textContent=(current.display||current.answer)+' — '+current.explanation;queue.push({item:current,after:attempts.length+3});if(pauseMode){pauseStart=Date.now();document.querySelector('#notes').href='#report/'+encodeURIComponent(current.topic);document.querySelector('#continueBar').hidden=false;document.querySelector('#continue').focus();}else advanceTimer=setTimeout(next,state.settings.rfWrongDelayMs);}}
 function tick(){if(ended)return;const left=duration?Math.max(0,duration-elapsed()/1000):0;document.querySelector('#timer').textContent=(duration?Math.ceil(left)+'s':'∞')+(pauseStart?' · paused':'');document.querySelector('#score').textContent=attempts.filter(a=>a.ok).length+' correct / '+attempts.length;document.querySelector('#timebar').style.width=(duration?100*left/duration:100)+'%';if(duration&&left<=0)finish();}
 function finish(){if(ended)return;ended=true;clearInterval(timer);clearTimeout(advanceTimer);const score=attempts.filter(a=>a.ok).length;state.rapidfire.sessions.push({t:Date.now(),dur:duration,score,acc:attempts.length?score/attempts.length:0});save();results(attempts);}
 input.oninput=()=>answer(false);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();answer(true);}};document.querySelector('#finish').onclick=finish;document.querySelector('#continue').onclick=()=>{if(pauseStart)next();};const giveup=document.querySelector('#giveup');giveup.onmousedown=e=>e.preventDefault();giveup.onclick=()=>{if(locked||ended)return;input.value='';answer(true);};const timer=setInterval(tick,100);register(e=>{if(e.key==='Escape'&&!ended){e.preventDefault();finish();}else if(current&&current.choices&&!locked&&/^[1-4]$/.test(e.key)){e.preventDefault();choose(+e.key-1);}else if(pauseStart&&(e.key==='Enter'||e.key===' ')){e.preventDefault();next();}},()=>{if(!ended)finish();clearInterval(timer);clearTimeout(advanceTimer);});next();}
function results(attempts){const good=attempts.filter(a=>a.ok).length,bank=missBank(state.rapidfire.attempts).length;app.innerHTML=`<div class="eyebrow">Session complete</div><h1>${good} correct.</h1><p>${attempts.length?Math.round(100*good/attempts.length):0}% accuracy · ${(median(attempts.map(a=>a.ms))/1000).toFixed(1)}s median response</p><div class="toolbar"><button id="again" class="primary">Drill again</button><button id="bank" ${bank?'':'disabled'}>Review miss bank (${bank})</button><a href="#report"> Review weak topics →</a></div><h2>By category</h2>${summary(attempts,'cat')}<h2>By topic</h2>${summary(attempts,'topic')}${attempts.some(a=>a.note)?`<h2>Notes</h2>${attempts.filter(a=>a.note).map(a=>`<p class="muted"><strong>${esc(a.prompt.split('\n')[0])}</strong> — you said “${esc(a.given)}”. ${esc(a.note)}</p>`).join('')}`:''}<h2>Misses this session (${attempts.length-good})</h2>${attempts.filter(a=>!a.ok).map(a=>`<details class="panel"><summary style="white-space:pre-line">${formatPrompt(a.prompt)}</summary><p>Your answer: ${esc(a.given||'(blank)')}</p><p>Answer: ${esc(a.expected)}. ${esc(a.explanation)}</p><a href="#report/${encodeURIComponent(a.topic)}">Go to notes</a></details>`).join('')||'<p>No misses this session.</p>'}`;document.querySelector('#again').onclick=setup;document.querySelector('#bank').onclick=()=>{missIndex=0;missCat='';misses();};register(()=>{});}
function summary(attempts,key){return '<table><tr><th>'+key+'</th><th>Accuracy</th><th>Median</th></tr>'+[...new Set(attempts.map(a=>a[key]))].map(k=>{const a=attempts.filter(x=>x[key]===k);return `<tr><td>${esc(key==='cat'?labels[k]:data.topics.find(t=>t.id===k)?.title||k)}</td><td>${a.filter(x=>x.ok).length}/${a.length}</td><td>${(median(a.map(x=>x.ms))/1000).toFixed(1)}s</td></tr>`;}).join('')+'</table>';}
