import {app,data,register,sections,options} from './app.js';
import {state,save,mastery} from './store.js';
import {esc,markdown} from './math.js';
export function report(){
 const rows=data.topics.map(t=>({...t,...mastery(t.id,data.flashcards,data.problems)})).sort((a,b)=>Number(a.studied)-Number(b.studied)||a.mastery-b.mastery||a.order-b.order);
 const studied=rows.filter(t=>t.studied).length,average=rows.reduce((n,t)=>n+t.mastery,0)/(rows.length||1);
 app.innerHTML=`<div class="eyebrow">03 / Understand</div><h1>Turn gaps into strengths.</h1><p class="lead">Your complete study guide, ordered by what needs the most attention. Unstudied topics come first.</p><div class="stats"><span><strong>${Math.round(average*100)}%</strong> overall mastery</span><span><strong>${studied}/${rows.length}</strong> topics studied</span><span>40% cards · 40% rapid-fire · 20% problems</span></div><div class="toolbar"><button id="collapse">Collapse all</button><button id="expand">Expand all</button><button id="print">Print / Save as PDF</button><label>Find topic <input id="searchNotes" type="search" placeholder="e.g. contradiction"></label></div><div class="weak-strip toolbar">${rows.slice(0,5).map(t=>`<a href="#report/${encodeURIComponent(t.id)}">${esc(t.title)} ${Math.round(t.mastery*100)}%</a>`).join(' · ')}</div><p id="emptyNotes" hidden>No matching topics.</p>${rows.map((t,i)=>`${!t.studied&&(i===0)?'<h2>Not yet studied</h2>':''}${t.studied&&(i===0||!rows[i-1].studied)?'<h2>Studied · weakest to strongest</h2>':''}<details open class="topic ${i===0||rows[i-1].section!==t.section?'section-start':''}" id="note-${esc(t.id)}" data-search="${esc((t.title+' '+t.section+' '+t.notes).toLowerCase())}"><summary>§${t.section} · ${esc(t.title)} <small>— ${Math.round(t.mastery*100)}%</small></summary><div class="meter"><span style="width:${100*t.mastery}%"></span></div><div class="stats"><small>${t.attempts} attempts</small><small>Rapid-fire: ${t.accuracy===null?'—':Math.round(t.accuracy*100)+'%'} accuracy</small><small>${t.median?(t.median/1000).toFixed(1)+'s':'—'} median</small><small>Trend ${t.trend===null?'—':t.trend>.05?'↑':t.trend<-.05?'↓':'→'}</small></div><div class="notes">${markdown(t.notes)}</div><a href="#problems/${encodeURIComponent(t.id)}">Practice this topic →</a></details>`).join('')}`;
 const all=()=>[...document.querySelectorAll('details.topic')];document.querySelector('#collapse').onclick=()=>all().forEach(d=>d.open=false);document.querySelector('#expand').onclick=()=>all().forEach(d=>d.open=true);
 const beforePrint=()=>all().forEach(d=>{d.open=true;d.hidden=false;});addEventListener('beforeprint',beforePrint);document.querySelector('#print').onclick=()=>{beforePrint();window.print();};
 document.querySelector('#searchNotes').oninput=e=>{let count=0;all().forEach(d=>{d.hidden=!d.dataset.search.includes(e.target.value.toLowerCase());if(!d.hidden)count++;});document.querySelector('#emptyNotes').hidden=!!count;};
 const target=decodeURIComponent(location.hash.split('/')[1]||'');if(target)requestAnimationFrame(()=>document.getElementById('note-'+target)?.scrollIntoView({block:'start'}));register(()=>{},()=>removeEventListener('beforeprint',beforePrint));
}
let filters={section:'',source:'',topic:'',difficulty:'',unattempted:false,wrong:false},selected=null,solution=false,hints=0;
export function problems(){const target=decodeURIComponent(location.hash.split('/')[1]||'');if(target){filters.topic=target;selected=null;}render();}
function filtered(){const order={textbook:0,homework:1,class:2,generated:3};return data.problems.filter(p=>(!filters.section||p.section===filters.section)&&(!filters.source||p.source===filters.source)&&(!filters.topic||p.topic===filters.topic)&&(!filters.difficulty||p.difficulty==filters.difficulty)&&(!filters.unattempted||!state.problems[p.id]?.attempts.length)&&(!filters.wrong||state.problems[p.id]?.attempts.at(-1)?.grade===1)).sort((a,b)=>order[a.source]-order[b.source]||sections.indexOf(a.section)-sections.indexOf(b.section)||a.difficulty-b.difficulty||a.id.localeCompare(b.id,undefined,{numeric:true}));}
function render(){const list=filtered();if(!list.some(p=>p.id===selected)){selected=list[0]?.id;solution=false;hints=0;}const p=list.find(p=>p.id===selected),i=list.indexOf(p),status=id=>{const grade=state.problems[id]?.attempts.at(-1)?.grade;return grade===3?'✓':grade===2?'◐':grade===1?'×':'○';};
 app.innerHTML=`<div class="eyebrow">04 / Put it on paper</div><h1>Problem grind</h1><div class="toolbar"><label>Section <select id="pgSection">${options(['',...sections],filters.section)}</select></label><label>Source <select id="pgSource">${options(['','textbook','homework','class','generated'],filters.source)}</select></label><label>Difficulty <select id="pgDifficulty">${options(['','1','2','3'],filters.difficulty)}</select></label><label>Topic <select id="pgTopic"><option value="">All</option>${data.topics.map(t=>`<option value="${esc(t.id)}" ${filters.topic===t.id?'selected':''}>${t.section} · ${esc(t.title)}</option>`).join('')}</select></label><label><input type="checkbox" id="unattempted" ${filters.unattempted?'checked':''}> Unattempted</label><label><input type="checkbox" id="wrong" ${filters.wrong?'checked':''}> Wrong only</label><button id="clearFilters">Clear filters</button></div><p class="muted">${list.length} matching problems · textbook → homework → class → generated · ${p?i+1:0}/${list.length}</p><div class="workspace"><aside class="problem-list" aria-label="Problem list">${list.map(q=>`<button data-problem="${esc(q.id)}" class="${q.id===selected?'selected':''}">${status(q.id)} ${esc(q.ref)}</button>`).join('')}</aside><section>${p?`<h2>${esc(p.ref)}</h2><p class="muted">${esc(p.source)} · difficulty ${p.difficulty} · <a href="#report/${encodeURIComponent(p.topic)}">Topic notes</a></p><div class="split"><div class="panel notes">${markdown(p.prompt)}</div><label>Your scratch work<textarea id="scratch" placeholder="Write your proof here, or work on paper. Your notes save as you type.">${esc(state.problems[p.id]?.scratch||'')}</textarea></label></div><div class="toolbar"><button id="previous">P · Previous</button><button id="nextProblem">N · Next</button><button id="hint" ${hints>=p.hints.length?'disabled':''}>H · Show hint</button><button id="solution">S · ${solution?'Hide':'Show'} solution</button></div>${p.hints.slice(0,hints).map(h=>`<p class="notice">${esc(h)}</p>`).join('')}${solution?`<div class="panel notes"><h3>Worked solution</h3>${markdown(p.solution)}</div><div class="toolbar"><span>Grade your own work:</span><button data-grade="1">1 · Wrong</button><button data-grade="2">2 · Partly</button><button data-grade="3">3 · Right</button></div>`:'<p class="muted">Try the problem before revealing the solution. Then give yourself an honest grade.</p>'}`:'<div class="panel"><h2>No matching problems</h2><p>Clear a filter to broaden the selection.</p></div>'}</section></div>`;
 for(const [id,key] of [['pgSection','section'],['pgSource','source'],['pgDifficulty','difficulty'],['pgTopic','topic'],['unattempted','unattempted'],['wrong','wrong']])document.getElementById(id).onchange=e=>{filters[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;selected=null;render();};document.querySelector('#clearFilters').onclick=()=>{filters={section:'',source:'',topic:'',difficulty:'',unattempted:false,wrong:false};selected=null;render();};
 const choose=id=>{selected=id;solution=false;hints=0;render();},move=n=>{if(list.length)choose(list[(i+n+list.length)%list.length].id);};document.querySelectorAll('[data-problem]').forEach(b=>b.onclick=()=>choose(b.dataset.problem));
 const toggle=()=>{solution=!solution;render();},hint=()=>{hints=Math.min(hints+1,p?.hints.length||0);render();},grade=g=>{if(!solution||!p)return;const entry=state.problems[p.id]||{attempts:[],scratch:''};entry.attempts.push({t:Date.now(),grade:g});state.problems[p.id]=entry;save();move(1);};
 if(p){document.querySelector('#scratch').oninput=e=>{const entry=state.problems[p.id]||{attempts:[],scratch:''};entry.scratch=e.target.value;state.problems[p.id]=entry;save();};document.querySelector('#previous').onclick=()=>move(-1);document.querySelector('#nextProblem').onclick=()=>move(1);document.querySelector('#solution').onclick=toggle;document.querySelector('#hint').onclick=hint;document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(+b.dataset.grade));}
 register(e=>{if(!p)return;const key=e.key.toLowerCase();if(key==='n')move(1);if(key==='p')move(-1);if(key==='s')toggle();if(key==='h')hint();if(/^[1-3]$/.test(key))grade(+key);});
}
