import {fresh,mastery,validate,missBank} from './store.js';
import {matches,parse,canonical,methodCanonical,extendable} from './normalize.js';
import {choices,nextRound,shuffle,mark,status,distance} from './learn.js';
import {argument,show,generators,full,methodGenerate,setMethodBank,bookForm,bookRules,setRuleForm} from './generators.js';
import {evaluate} from './normalize.js';
import {state} from './store.js';
const results=[];export function test(name,fn){try{if(!fn())throw Error('Assertion false');results.push('PASS '+name);}catch(e){results.push('FAIL '+name+': '+e.message);}document.querySelector('#results').textContent=results.join('\n');document.title=results.some(r=>r.startsWith('FAIL'))?'FAIL':'PASS';}
test('Empty progress has zero mastery',()=>mastery('t',[],[],fresh()).mastery===0);
test('Unrated cards count as zero',()=>{const s=fresh();s.flashcards.a={lastRating:'easy',seen:1};return mastery('t',[{id:'a',topic:'t'},{id:'b',topic:'t'}],[],s).mastery===.2;});
test('Mastery weights and Laplace smoothing',()=>{const s=fresh();s.flashcards.a={lastRating:'easy',seen:1};s.rapidfire.attempts=[{topic:'t',ok:true,ms:1000}];s.problems.p={attempts:[{grade:3}]};return Math.abs(mastery('t',[{id:'a',topic:'t'}],[{id:'p',topic:'t'}],s).mastery-(.4+.4*2/3+.2))<1e-10;});
test('Reject bad import',()=>{try{validate({version:2});return false;}catch{return true;}});
for(const s of ['~p v q','¬p ∨ q','q or not p','(q | !p)'])test('Canonical OR: '+s,()=>matches(s,'¬p ∨ q','symbolic'));
for(const s of ['p ^ q','q & p','q and p'])test('Canonical AND: '+s,()=>matches(s,'p ∧ q','symbolic'));
test('Implication direction retained',()=>!matches('q -> p','p → q','symbolic'));
test('Associative flattening',()=>matches('r and (q and p)','(p ∧ q) ∧ r','symbolic'));
test('Quantifier aliases and power',()=>matches('E x A y (x^2 + y != 2)','∃x ∀y (x^2 + y ≠ 2)','symbolic'));
test('Arithmetic power is not conjunction',()=>!matches('x^2','x ∧ 2','symbolic'));
test('Implicit multiplication',()=>matches('2*k+1','2k+1','symbolic'));
test('Malformed input rejected',()=>!matches('p or','p','symbolic'));
test('Unknown characters rejected',()=>!matches('p @','p','symbolic'));
test('Quantifier order retained',()=>!matches('forall x exists y (x < y)','exists y forall x (x < y)','symbolic'));
for(const [a,b] of [['dm',"de morgan’s"],['7.1','conditional disjunction'],['mp','modus ponens'],['Y','yes'],['TRUE','T']])test('Text aliases '+a,()=>matches(a,b));
for(const s of ['x²+1','x^2+1','(x)² + 1'])test('Superscript square: '+s,()=>matches(s,'x^2 + 1','symbolic'));
test('Superscript cube',()=>matches('n³ - n','n^3 - n','symbolic'));
test('Superscript square is not conjunction',()=>!matches('x²','x ∧ 2','symbolic'));
test('Superscript square differs from x2 identifier',()=>!matches('x²','x2','symbolic'));
for(const s of ['∀xP(x)','∀x P(x)','forall xP(x)','AxP(x)','Ax P(x)','∀XP(X)'])test('Glued quantifier variable: '+s,()=>matches(s,'∀x P(x)','symbolic'));
test('Glued nested quantifiers',()=>matches('∃x∀y(x<y)','Ex Ay(x<y)','symbolic'));
test('Quantifier with parenthesised body',()=>matches('∀x(P(x))','∀x P(x)','symbolic'));
test('Negated glued quantifier',()=>matches('¬∀xP(x)','not forall x P(x)','symbolic'));
test('Glued quantifier keeps order',()=>!matches('∀x∃yP(x,y)','∃y∀xP(x,y)','symbolic'));
test('Glued letters after quantifier split as variable then body',()=>canonical(parse('∀xy'))==='∀x(y)');

test('Learn status accepted by validate',()=>{const s=fresh();s.flashcards.a={box:1,lastRating:'again',lastSeen:1,seen:1,learn:'learning'};return validate(s)===s;});
test('Bad learn status rejected',()=>{const s=fresh();s.flashcards.a={box:1,lastRating:'again',lastSeen:1,seen:1,learn:'maybe'};try{validate(s);return false;}catch{return true;}});
const deck=[{id:'fc-1.1-a-0',topic:'1.1-a',back:'A'},{id:'fc-1.1-a-1',topic:'1.1-a',back:'B'},{id:'fc-1.1-a-2',topic:'1.1-a',back:'B'},{id:'fc-1.1-b-0',topic:'1.1-b',back:'C'},{id:'fc-1.3-c-0',topic:'1.3-c',back:'D'},{id:'fc-1.3-c-1',topic:'1.3-c',back:'A'}];
const seq=()=>{let n=0;return()=>((n+=7)%11)/11;};
test('Learn choices: four options, card included, backs distinct',()=>{const o=choices(deck[0],deck,4,seq());return o.length===4&&o.some(x=>x.id===deck[0].id)&&new Set(o.map(x=>x.back)).size===4;});
test('Learn choices prefer same topic, then section',()=>{const o=choices(deck[0],deck,4,seq()).filter(x=>x.id!==deck[0].id);return o.some(x=>x.topic==='1.1-a')&&o.some(x=>x.id==='fc-1.1-b-0');});
test('Learn choices never exceed available distinct backs',()=>choices(deck[4],deck.slice(4),4,seq()).length===2&&choices(deck[1],[deck[1],deck[2]],4,seq()).length===1);
test('Shuffle preserves elements',()=>shuffle([1,2,3,4],seq()).sort().join()==='1,2,3,4');
test('Learn round skips known cards and puts still-learning first',()=>{const keep=state.flashcards;state.flashcards={'fc-1.1-a-0':{learn:'known'},'fc-1.3-c-0':{learn:'learning'}};const r=nextRound(deck,seq());state.flashcards=keep;return r.length===5&&r[0].id==='fc-1.3-c-0'&&!r.some(c=>c.id==='fc-1.1-a-0');});
test('Mark known raises the box and stores status',()=>{const keep=state.flashcards;state.flashcards={};mark('x',true);const v=state.flashcards.x;const ok=v.box===2&&v.learn==='known'&&v.lastRating==='good';mark('x',false);const ok2=state.flashcards.x.box===1&&state.flashcards.x.learn==='learning';state.flashcards=keep;localStorage.removeItem('math381.v1');return ok&&ok2;});
test('Argument prompt stacks premises and conclusion',()=>argument('p → q; ¬q ∴ ¬p')==='p → q\n¬q\n∴ ¬p'&&argument('p ∴ p ∨ q')==='p\n∴ p ∨ q');
test('Miss bank keeps only prompts whose latest attempt is wrong, newest first',()=>{const b=missBank([{t:1,prompt:'A',ok:false},{t:2,prompt:'B',ok:false},{t:3,prompt:'A',ok:true},{t:4,prompt:'C',ok:false}]);return b.map(a=>a.prompt).join()==='C,B';});
test('Pause setting (0 ms) is valid',()=>{const s=fresh();s.settings.rfWrongDelayMs=0;return validate(s)===s;});
test('Minimal parentheses printer',()=>show({o:'∨',l:{n:{a:'p'}},r:{o:'∧',l:{a:'q'},r:{a:'r'}}})==='¬p ∨ (q ∧ r)'&&show({o:'∧',l:{o:'∧',l:{a:'p'},r:{a:'q'}},r:{a:'r'}})==='p ∧ q ∧ r'&&show({o:'→',l:{a:'p'},r:{o:'→',l:{a:'q'},r:{a:'r'}}})==='p → (q → r)'&&show({n:{o:'∨',l:{a:'p'},r:{a:'q'}}})==='¬(p ∨ q)');
test('Generated truth prompts are minimal and evaluate to their answer',()=>{for(let k=0;k<200;k++){const it=generators.truth(),[env,ex]=it.prompt.split('\n'),e=ex.replace('Evaluate ',''),vals=Object.fromEntries(env.split(', ').map(x=>[x[0],x.endsWith('T')]));const wrapped=e=>{if(e[0]!=='(')return false;let d=0;for(let i=0;i<e.length;i++){if(e[i]==='(')d++;if(e[i]===')')d--;if(!d)return i===e.length-1;}return false;};if(wrapped(e)||/¬\([a-z]\)|(?<![¬a-z])([a-z]) [∧∨→↔⊕] \1\b/.test(e))throw Error(e);if((evaluate(parse(e),vals)?'T':'F')!==it.answer)throw Error('eval '+e);}return true;});
test('Set order follows topic order then priority',()=>{const o={a:1,b:2};const cs=[{id:'fc-1.1-b-0',topic:'b',priority:1},{id:'fc-1.1-a-1',topic:'a',priority:2},{id:'fc-1.1-a-0',topic:'a',priority:1},{id:'fc-1.3-x',topic:'a',priority:1}].filter(c=>c.id.split('-')[1]==='1.1').sort((x,y)=>(o[x.topic]||0)-(o[y.topic]||0)||x.priority-y.priority);return cs.map(c=>c.id).join()==='fc-1.1-a-0,fc-1.1-a-1,fc-1.1-b-0';});
test('Learn distractors match the answer shape',()=>{const laws=[['dist','Distributive.','p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r)\np ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)'],['comm','Commutative.','p ∨ q ≡ q ∨ p\np ∧ q ≡ q ∧ p'],['idem','Idempotent.','p ∨ p ≡ p\np ∧ p ≡ p'],['dn','Double negation.','¬¬p ≡ p'],['abs','Absorption.','p ∨ (p ∧ q) ≡ p\np ∧ (p ∨ q) ≡ p']];const deck=laws.flatMap(([k,name,forms])=>[{id:'fc-1.3-'+k+'-recall',topic:'1.3-'+k,back:name},{id:'fc-1.3-'+k+'-definition',topic:'1.3-'+k,back:forms}]);const o=choices(deck[1],deck,4,seq());return o.length===4&&o.every(x=>x.back.includes('≡'))&&choices(deck[0],deck,4,seq()).every(x=>!x.back.includes('≡'));});
test('Shape distance: name vs formula is far, formula vs formula is near',()=>distance('Distributive.','p ∨ q ≡ q ∨ p')>distance('p ∧ q ≡ q ∧ p','p ∨ q ≡ q ∨ p'));
test('Rule and law answers display full names',()=>full('conj')==='Conjunction (conj)'&&full('res')==='Resolution (res)'&&full('identity')==='Identity'&&generators.rule().display.length>4&&matches('conj',generators.conj?'x':'conj'));
for(const [a,b] of [['cp','contraposition'],['C.P.','contraposition'],['contrapositive','contraposition'],['by contradiction','contradiction'],['BWOC','contradiction'],['ci','contradiction-implication'],['assume p and not q','contradiction-implication'],['contradiction of an implication','contradiction-implication'],['iff','biconditional'],['both directions','biconditional'],['cycle','tfae'],['the following are equivalent','tfae'],['disprove','counterexample'],['ce','counterexample'],['direct proof','direct'],['d','direct']])test('Method alias '+a,()=>matches(a,b,'method'));
test('Method aliases do not cross',()=>!matches('contradiction','contradiction-implication','method')&&!matches('cp','contradiction','method'));
test('Generated method items are well formed',()=>{for(let k=0;k<150;k++){const it=methodGenerate();if(!it)continue;if(!it.prompt||!it.accepted.length||!it.explanation||it.type!=='method')throw Error(it.prompt);if(/Prove or disprove/.test(it.prompt)&&it.accepted[0]==='counterexample'&&/irrational number is irrational|is (even|odd)$/.test(it.prompt)===false&&false)throw Error(it.prompt);}return true;});
fetch('content/rapidfire.json').then(r=>r.json()).then(j=>{const bank=j.method,by=Object.fromEntries(bank.map(b=>[b.prompt,b.accepted]));test('Method bank has at least 60 items',()=>bank.length>=60&&bank.every(b=>b.id&&b.cat==='method'&&b.prompt&&b.accepted.length&&b.why));const fixed=[['If n is an integer and 3n + 2 is odd, then n is odd.','contraposition'],['If m and n are both even integers, then m + n is even.','direct'],['√2 is irrational.','contradiction'],['If x is irrational and y is rational, then x + y is irrational.','contradiction-implication'],['An integer n is odd if and only if n² is odd.','biconditional'],['Show that for an integer n these are equivalent: (i) n is even; (ii) n − 1 is odd; (iii) n² is even.','tfae'],['Prove or disprove: the product of two irrational numbers is irrational.','counterexample'],['If m and n are integers and mn is even, then m is even or n is even.','contraposition'],['If n is a perfect square, then n + 2 is not a perfect square.','contradiction-implication'],['There is no largest even integer.','contradiction'],['Prove or disprove: the product of two rational numbers is rational.','direct'],['If n is an integer and n² is even, then n is even.','contraposition']];for(const [p,m] of fixed)test('Method item: '+p.slice(0,50),()=>by[p]&&by[p][0]===m);test('Secondary methods listed after the primary',()=>by['If n is an integer and n² is even, then n is even.'].join()==='contraposition,contradiction');});
test('Book form matches Table 1 layout',()=>bookForm(bookRules.mp)==='p\np → q\n---\n∴ q'&&bookForm(bookRules.add)==='p\n---\n∴ p ∨ q');
test('Book mode shows p, q, r only; renamed mode may not',()=>{setRuleForm('book');for(let k=0;k<40;k++){const it=generators.rule();if(!/^Name the rule:\n/.test(it.prompt)||/[abst]/.test(it.prompt.split('\n').slice(1).join('')))throw Error(it.prompt);}setRuleForm('renamed');return true;});
test('Name the rule never asks about a fallacy',()=>{for(let k=0;k<80;k++)if(generators.rule().answer==='invalid')return false;return true;});
test('Prefix guard: dom waits, domination and mp fire',()=>extendable('dom')&&!extendable('domination')&&!extendable('mp')&&extendable('d','method')&&!extendable('direct proof','method')&&!extendable('zzz'));
test('Rules listed in Table 1 order',()=>argument('¬q; p → q ∴ ¬p')==='¬q\np → q\n∴ ¬p'&&bookForm(bookRules.mt)==='¬q\np → q\n---\n∴ ¬p');
